blogpost_website/urls.py
from django.contrib import admin
from django.urls import path, include

import debug_toolbar

urlpatterns = [
    path('admin/', admin.site.urls),
    path('posts/', include('posts.urls', namespace='posts')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('__debug__/', include(debug_toolbar.urls)),
]

posts/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required
from posts.views import PostView, DeletePostView, UpdatePostView, new_post

app_name = 'posts'

urlpatterns = [
    path('home/', login_required(PostView.as_view(template_name="home.html")), name='posts'),
    path('new/', login_required(new_post), name='add_post'),
    path('<int:pk>/update', login_required(UpdatePostView.as_view()), name='update_post'),
    path('<int:pk>/delete', login_required(DeletePostView.as_view()), name='delete_post'),
]

posts/models.py
# from django.conf import settings
from django.contrib.auth.models import User
from django.db import models

# Create your models here.
from django.urls import reverse


class Post(models.Model):

    creator = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        verbose_name='Автор записи',
    )

    title = models.CharField(
        max_length=50,
        verbose_name='Заголовок поста',
    )

    text = models.TextField(
        blank=False,
        null=False,
        verbose_name='Текст статьи'
    )

    created_at = models.DateTimeField(
        auto_now_add=True,
        verbose_name='Дата создания',
    )

    updated_at = models.DateTimeField(
        auto_now=True,
        verbose_name='Дата обновления',
    )

    class Meta:
        verbose_name = 'Запись'
        verbose_name_plural = 'Записи'

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('posts:posts')

posts/forms.py
from django import forms

from posts.models import Post
from django.contrib.auth.models import User


class PostForm(forms.ModelForm):
    creator = forms.ModelChoiceField(
        queryset=None,
        empty_label=None,
    )

    class Meta:
        model = Post
        fields = ['title', 'text']

    def __init__(self, user, *args, **kwargs):
        super(PostForm, self).__init__(*args, **kwargs)
        self.fields['creator'].queryset = User.objects.filter(id=user.id)

posts/views.py
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView, UpdateView, DeleteView
from rest_framework.exceptions import PermissionDenied

from posts.forms import PostForm
from posts.models import Post


class PostView(ListView):
    model = Post
    template_name = 'home.html'


class PostDetailView(DetailView):
    model = Post
    template_name = 'post_details.html'


def new_post(request):
    if request.method == 'POST':
        form = PostForm(request.user, request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.creator = request.user
            post.save()
            return redirect('posts:posts')
    else:
        form = PostForm(request.user)
    return render(request, 'add_post.html', {'form': form})


class UpdatePostView(UpdateView):
    model = Post
    template_name = 'update_post.html'
    fields = ['title', 'text']

    def get_object(self, *args, **kwargs):
        obj = super(UpdatePostView, self).get_object(*args, **kwargs)
        if not obj.creator == self.request.user:
            raise PermissionDenied
        return obj


class DeletePostView(DeleteView):
    model = Post
    template_name = 'delete_post.html'
    success_url = reverse_lazy('posts:posts')

    def get_object(self, *args, **kwargs):
        obj = super(DeletePostView, self).get_object(*args, **kwargs)
        if not obj.creator == self.request.user:
            raise PermissionDenied
        return obj

templates/add_post.html
{% extends "base.html" %}
{% block content %}
{% block body %}


<div class="col-md-12 text-center">
    <h2>Добавить новую запись</h2>
    <br/>
    <div class="form-group">
        <form method="POST">
            {% csrf_token %}
            <h4>Заголовок {{ form.title }}</h4>
            <br/>
            <h3>Текст: <br/><br/> {{ form.text }}</h3>
            <br/>
            <h6 class="text-black-50">Автор статьи: {{ form.creator }}</h6>
            <br/><br/>
            <button class="btn btn-primary">Сохранить</button>
        </form>
    </div>
</div>

{% endblock %}
{% endblock %}

templates/base.html
<!doctype html>
<html>
    <head>
        {% load static %}
        {% block head %}

        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="
        sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

        <title></title>
        {% endblock %}
    </head>
    <body>
        {% block body %}
        <h1>BASE</h1>
        {% endblock %}

        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="
        sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    </body>
</html>

templates/delete_post.html
{% extends "base.html" %}
{% block content %}
{% block body %}

<div class="col-md-12 text-center">
    <h2>Удалить запись?</h2>
    <br/>
    <h4>{{ post.title }}</h4>
<br/>
    <div class="form-group">
        <form method="POST">
            {% csrf_token %}
            <strong>Вы уверены, что хотите удалить запись?</strong>
            <br/><br/>
            <button class="btn btn-danger">ДА</button>
        </form>
    </div>
</div>

{% endblock %}
{% endblock %}

templates/home.html
{% extends "base.html" %}
{% block content %}
{% block body %}

<div>
    <br/>
    <a href="{% url 'posts:add_post' %}"><button type="button" class="btn btn-primary btn-lg">Добавить новую запись </button></a>
</div>

<div class="col-md-12 text-center">
        <h1>Все записи</h1>
        <hr class="mt-0 mb-4">
</div>
<div>
    {% for post in object_list %}
        <ul class="list-group list-group-flush">
             <li class="list-group-item list-group-item-success"><h4>{{ post.title }}<span class="badge bg-secondary">(Автор: {{ post.creator }})</span></h4></li>
             <li class="list-group-item"> {{ post.text }}</li>
        </ul>
        {% if user == post.creator %}
                <button type="button" class="btn btn-danger"><a href="{% url 'posts:delete_post' post.pk %}">Удалить</a></button>
                <button type="button" class="btn btn-warning"><a href="{% url 'posts:update_post' post.pk %}">Редактировать</a></button>
        {% endif %}
        <hr class="mt-0 mb-4">
    {% endfor %}
</div>

{% endblock %}
{% endblock %}

templates/update_post.html
{% extends "base.html" %}
{% block content %}
{% block body %}

<div class="col-md-12 text-center">
    <h2>Изменение записи</h2>
    <br/>
    <h4>{{ post.title }}</h4>
    <br/>

    <div class="form-group">
        <form method="POST">
            {% csrf_token %}
            {{ form.as_p }}
            <br/><br/>
            <button class="btn btn-secondary">Сохранить изменения</button>
        </form>
    </div>
</div>


{% endblock %}
{% endblock %}